### ISSUE TITLE
You are passing an authorization header in with your apiKey. Just pass in the apiKey

### ISSUE THREAD

**Issue by chrisdhaan** [Pigpocket/MartiniFinder#3]
https://github.com/Pigpocket/MartiniFinder/blob/4d1d777047ba3e653ce222eea1a4dbf770b657d4/MartiniFinder/Controllers/MapViewController.swift#L125

**Comment by Pigpocket** [comment]
Ok. Done.

**Comment by Pigpocket** [comment]
OK. I have located this declaration in the struct inside my YelpClient class extension, so it is globally available (I declared it in the view controller just for the sake of testing if it worked). I am receiving the following error message now:

`searchBusinesses(byTerm) error:  An access token must be supplied in order to use this endpoint.`

Is this related to an OAuth 2.0 authentication process in your code? I see this in the documentation about them no longer using tokens, and just the APIKey:

> Where did my client secret go?
> Prior to December 7, 2017 the API used OAuth 2.0 to authenticate requests to the API. In an effort to simplify authentication, starting March 1, 2018 the API no longer uses OAuth 2.0 for requests and moved over to only API Keys.
> 
> With OAuth 2.0 the process to authenticate was:
> 
> Get your Client ID and client secret from the Manage App page.
> Make a request to the token endpoint with your Client ID and client secret to get an access token.
> Put the access token inside of the request header as "Authorization: Bearer <YOUR ACCESS TOKEN>" and make requests against the API.
> With just API Keys the process to authenticate is:
> 
> Get your API Key from the Manage App page.
> Put the API Key in the request header as "Authorization: Bearer <YOUR API KEY>".
> And that's it! You no longer need to make a request to the token endpoint to get an access token. Your API Key does not expire like the access tokens used to, so you don't need to worry about generating new ones. Note that the API Key is not a drop in replacement for the client secret. Using the API Key as a client secret in the token endpoint will not work.
> 
> Migrating your app to use API Keys
> For both OAuth 2.0 and API Keys the authorization header structure is exactly the same. Your previously generated access token has automatically been converted to be your non-expiring API Key. What you need to do depends on how you authenticated:
> 
> If you were caching your access tokens, the only change you need to make is to remove the call to the old token endpoint. Everything else should work seamlessly.
> If you were making a request to the token endpoint for every API request, you need to remove the intermediary request to the token endpoint and store your API Key in your app. Use the API Key in the same place you were using the access token returned by the token endpoint. 

I looked through your method but couldn't find anything about the token. Or perhaps I'm missing something. I've also added you as a contributor if that's easier.

**Comment by chrisdhaan** [comment]
Just pass this as the apiKey `8UOe63-UqKM8syYDjMXsdbJbMXWg1Hp6Tu0_kgQr_wUMP3Y2NEDXZE_Tdc_C_xSjihkl2PeM3n9sveqQ1bdXm2AQ1bviVEo1qpUbAk9m_3CmQv3wSlnYZ8qp5j5RWnYx`
